SRC += jensomato.c
SRC += casemodes.c
COMMAND_ENABLE = no # Commands for debug and configuration
UNICODE_ENABLE = no # Unicode
CONSOLE_ENABLE = no
EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
